import { Inter } from 'next/font/google'
import './globals.css'
import { NextUIProvider } from '@nextui-org/react'
import { ThemeProvider } from 'next-themes'
import ReduxProvider from '@/redux/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <title>Visibility Pack</title>
    </head>
    <body>
      <ThemeProvider
      attribute="class"
      defaultTheme="light"
      breakpoints={["xxl", "xl", "lg", "md", "sm", "xs"]}
      minBreakpoint= "xs">
        <NextUIProvider>
          <ReduxProvider>
            <div className="flex w-screen font-serif">
              {path === "/" ? null : <div> </div>} {children}
            </div>
          </ReduxProvider>
        </NextUIProvider>
      </ThemeProvider>
    </body>
  </html>
  )
}
